export const FETCH_LOGIN = 'FETCH_LOGIN';
export const FETCH_MY_MUSIC_LIST = 'FETCH_MY_MUSIC_LIST';
export const FETCH_RECOMMEND_MUSIC_LIST = 'FETCH_RECOMMEND_MUSIC_LIST';
export const FETCH_DELETE_MUSIC = 'FETCH_DELETE_MUSIC';
export const FETCH_SUBMIT_MUSIC_NAME = 'FETCH_SUBMIT_MUSIC_NAME';
