export const FEFRESH_DATA = 'FEFRESH_DATA';
export const CANCUL_LEFT_NUM = 'CANCUL_LEFT_NUM';
export const CANCUL_RIGHT_NUM = 'CANCUL_RIGHT_NUM';
export const CANCUL_TOP_NUM = 'CANCUL_TOP_NUM';
export const CANCUL_BOTTOM_NUM = 'CANCUL_BOTTOM_NUM';

export const CHANCE_LEFT_KEY_NUM = 'CHANCE_LEFT_KEY_NUM';
