export const FETCH_LOGIN = 'FETCH_LOGIN';
export const FETCH_MY_MUSIC_LIST = 'FETCH_MY_MUSIC_LIST';
export const FETCH_RECOMMEND_MUSIC_LIST = 'FETCH_RECOMMEND_MUSIC_LIST';
export const FETCH_DELETE_MUSIC = 'FETCH_DELETE_MUSIC';
export const FETCH_SUBMIT_MUSIC_NAME = 'FETCH_SUBMIT_MUSIC_NAME';
export const FETCH_MARK_START = 'FETCH_MARK_START';
export const FETCH_MARK_END = 'FETCH_MARK_END';
export const FETCH_MARK_CLEAR = 'FETCH_MARK_CLEAR';
